### ISSUE TITLE
一些项目过时了

### ISSUE THREAD

**Issue by gtt116** [xiaohanyu/openstack-git-oschina-mirror#2]
Hi，

我发现有一些 openstack 项目过时了，比如 openstack/keystone, openstack/ironic。

**Comment by gtt116** [comment]
十分感谢一直维护着这个镜像，这对我们中国用户非常有用。
如果有什么我能帮上忙的，请让我知道。

**Comment by xiaohanyu** [comment]
今天看了下，github/openstack 下的 repo 竟然有 780 个了。而 git.oschina 还没有开放相应的 API ，我个人实在是没精力手工建立 700+ 个 git.oschina 的 repo 了……

等 git.oschina 的 API 开放后再搞。
